---
# Setup/install tasks
- include_tasks: install-talm-olm.yml
  when: talm["install_method"] == "olm"

- include_tasks: install-talm-source.yml
  when: talm["install_method"] == "source"

# Check TALM installation
- include_tasks: check-talm-install.yml
